aperitivos/urls.py
from django.urls import path
from aperitivos.views import videos, indice

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', videos, name='video'),
    path('', indice, name='indice'),
]

base/urls.py
from django.urls import path
from base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

modulos/urls.py
from django.urls import path

from modulos import views

app_name = 'modulos'
urlpatterns = [
    path('<slug:slug>', views.detalhe, name='detalhe'),
    path('aulas/<slug:slug>', views.aula, name='aula'),
    path('', views.indice, name='indice'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('base.urls')),
    path('aperitivos/', include('aperitivos.urls')),
    path('modulos/', include('modulos.urls')),
    path('turmas/', include('turmas.urls')),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

turmas/urls.py
from django.urls import path

from turmas import views

app_name = 'turmas'
urlpatterns = [
    path('', views.indice, name='indice'),
]

aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Vídeo: {self.titulo}'

base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

modulos/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel


class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey('Modulo', on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'
    vimeo_id = models.CharField(max_length=32)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:aula', kwargs={'slug': self.slug})

turmas/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.


class Turma(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    alunos = models.ManyToManyField(get_user_model(), through='Matricula')


class Matricula(models.Model):
    data = models.DateTimeField(auto_now_add=True)  # captura data e hora exatas no momento da inscrição.
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['usuario', 'turma']]
        ordering = ['turma', 'data']

aperitivos/views.py
from django.shortcuts import get_object_or_404, render
from aperitivos.models import Video


def indice(request):
    dict_videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'dict_videos': dict_videos})


def videos(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})

base/views.py
from django.shortcuts import render
from django.http import HttpResponse # noqa

# Create your views here.
from modulos import facade


def home(request):
    return render(request, 'base/home.html', {'MODULOS': facade.listar_modulos_ordenados()})

modulos/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from modulos import facade


def indice(request):
    ctx = {'modulos': facade.listar_modulos_com_aulas()}
    return render(request, 'modulos/indice.html', ctx)


def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    aulas = facade.listar_aulas_de_modulo_ordenadas(modulo)
    return render(request, 'modulos/modulo_detalhe.html', {'modulo': modulo, 'aulas': aulas})


@login_required
def aula(request, slug):
    aula = facade.enccontrar_aula(slug)
    return render(request, 'modulos/aula_detalhe.html', {'aula': aula})

turmas/views.py
from django.shortcuts import render

# Create your views here.


def indice(request):
    return render(request, 'turmas/indice.html')

aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock title %}
{% block description %}Página do curso Python Pro{% endblock description %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3">Lista de Vídeos Aperitivos</h1>
                <ol>
                    {% for video in dict_videos %}
                        <li><a href="{{ video.get_absolute_url }}">{{ video.titulo | default:"Faltando Título" }}</a>
                        </li>
                    {% empty %}
                        <li>Não foi encontrado nenhum vídeo de aperitivo</li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
{% endblock body %}

aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock title %}
{% block description %}Página do curso Python Pro{% endblock description %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3">{{ video.titulo | default:"Faltando Título" }}</h1>
                <div style="padding:56.25% 0 0 0;position:relative;">
                    <iframe
                            src="https://player.vimeo.com/video/{{ video.vimeo_id }}?h=8ce2ff83ce&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                            frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen
                            style="position:absolute;top:0;left:0;width:100%;height:100%;"
                            title="AULA 01 - MOTIVA&amp;Ccedil;&amp;Atilde;O &amp;mdash; Curso de Python Gr&amp;aacute;tis">
                    </iframe>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Python Pro{% endblock title %}</title>

    <meta name="description" content="{% block description %}Página do Curso Python Pro{% endblock description %}">
    <meta name="author" content="Henrique Lima">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Módulos
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for modulo in MODULOS %}
                            <li><a class="dropdown-item" href="{{ modulo.get_absolute_url }}">{{ modulo.titulo }}</a>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                        {% endfor %}
                    </ul>
                </li>

            </ul>
            {% if user.is_authenticated %}
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.first_name }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <div class="dropdown-item">
                                 <a class="btn btn-danger" href={% url 'logout' %}>Sair</a>
                            </div>
                        </div>
                    </li>
                </ul>
            {% else %}
                <a class="btn btn-light my-2" href="{% url 'login' %}">Entrar</a>
            {% endif %}
        </div>
    </div>
</nav>

{% block body %} {% endblock body %}

{% include 'base/footer.html' with contato_email='ramalho@python.pro.br' only %}

</body>
</html>

base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Entre em Contato.</h3>
                <address>
                    +55 12 997-411-855
                    <br/>
                    <a href="mailto:{{contato_email}}" class="text-light">{{contato_email}}</a>
                </address>
            </div>
        </div>
    </div>
    <div>
        <div class="rights pb-4">
            <div class="container">
                <div class="row">
                    <div class="col">
                        {% now 'Y' %} Python Pro. Todos os direitos reservados.
                    </div>
                </div>
            </div>
        </div>
    </div>

</footer>

base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Home{% endblock title %}

{% block body %}
    <div class="container" style="padding-top: 50px; padding-left: 0">
        <div class="jumbotron">
            <h2>
                Curso de Python com Luciano Ramalho
            </h2>
            <h4 class="mt-4">Matriculas Abertas! Custo R$ 1000,00</h4>
            <!-- INICIO DO BOTAO PAGSEGURO -->
            <a href="https://pag.ae/7X-_Rztjn/button" target="_blank" title="Pagar com PagSeguro"><img
                    src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/205x30-pagar.gif"
                    alt="Pague com PagSeguro - é rápido, grátis e seguro!"/></a>
            <!-- FIM DO BOTAO PAGSEGURO -->

            <!-- COMEÇO DO FORMULÁRIO -->
            {#   <h4 class="mt-4">Entre na fila de espera</h4> #}
            {#   <form action="https://python.us14.list-manage.com/subscribe/post?u=a4a0ca979dca7e0e3eb86818a&amp;id=66c54e7e68" #}
            {#   method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" #}
            {# class="form-row align-items-center" target="_blank" novalidate> #}
            {#    <div class="col-auto">#}
            {#   <label class="visible" for="mce-EMAIL">Email: </label>#}
            {#   <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL"#}
            {# placeholder="exemplo@email.com"> #}
            {#    </div>#}
            {#  <div class="col-auto"> #}
            {#  <label class="visible" for="mce-FNAME">Nome: </label>#}
            {#  <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME"#}
            {# placeholder="Seu Nome"> #}
            {#  </div> #}

            {#   <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->#}
            {#  <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" #}
            {# name="b_a4a0ca979dca7e0e3eb86818a_66c54e7e68"#}
            {# tabindex="-1" #}
            {# value=""></div> #}

            {#  <div class="col-auto mt-2">#}
            {#  <input type="submit" value="Salvar" name="subscribe"#}
            {# id="mc-embedded-subscribe" class="btn btn-primary"> #}
            {#   </div>#}
            {#   </form> #}
            <!-- FIM DO FORMULÁRIO -->
        </div>
        <div class="row">
            <div class="col-md-12" style="padding-left: 0; padding-top: 70px">
                <div class="card">
                    <h5 class="card-header">
                        Mais detalhes sobre o instrutor
                    </h5>
                    <div class="card-body">
                        <p class="card-text">
                            <img src="{% static 'img/luciano-ramalho.png' %}" alt="foto-luciano-ramalho"
                                 class="img-thumbnail float-start me-3"/>
                            Ramalho é sócio e professor na <a href="https://www.python.pro.br">Python
                            Pro</a> e
                            autor do Livro <a
                                href="https://www.oreilly.com/library/view/fluent-python-2nd/9781492056348/"
                                target="_blank">Python Fluente</a>. Foi diretor técnico do Brasil Online,
                            primeiro portal
                            da
                            Abril S/A na Web. Liderou times para os portais IDG Now, BOL, UOL, AOL Brasil e
                            outros,
                            usando Python desde 1998. Como instrutor, atendeu clientes como Citibank, CPqD,
                            Serpro,
                            Presidência da República, Globo.com e Itaú. Palestrante em eventos
                            internacionais
                            como
                            FISL, PyCon US e OSCON. Ajudou a criar a Associação Python Brasil e foi seu
                            presidente.
                            É membro da Python Software Foundation e fundador do Garoa Hacker Clube, o
                            primeiro
                            hackerspace do Brasil.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock title %}
{% block description %}Página do curso Python Pro{% endblock description %}
{% block body %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ aula.modulo.get_absolute_url }}">{{ aula.modulo.titulo }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ aula.titulo }}</li>
        </ol>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3">{{ aula.titulo | default:"Faltando Título" }}</h1>
                <iframe
                        src="https://player.vimeo.com/video/{{ aula.vimeo_id }}?h=8ce2ff83ce&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                        frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen
                        style=width:640px;height:360px;"
                        title="AULA 01 - MOTIVA&amp;Ccedil;&amp;Atilde;O &amp;mdash; Curso de Python Gr&amp;aacute;tis">
                </iframe>
            </div>
        </div>
    </div>

{% endblock body %}

modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ modulo.titulo }}{% endblock title %}
{% block description %}Página com detalhes do módulo {{ modulo.titulo }}{% endblock description %}
{% block body %}

    <div class="container">
        {% for modulo in modulos %}
            <div class="row">
                <div class="col-md-12">
                    <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
                    <dl>
                        <dt>Público</dt>
                        <dd>{{ modulo.publico }}</dd>
                        <dt>Descrição</dt>
                        <dd>{{ modulo.descricao }}</dd>
                    </dl>
                    <h2>Aulas</h2>
                    <ol>
                        {% for aula in modulo.aulas %}
                            <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock body %}

modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ modulo.titulo }}{% endblock title %}
{% block description %}Página com detalhes do módulo {{ modulo.titulo }}{% endblock description %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
                <dl>
                    <dt>Público</dt>
                    <dd>{{ modulo.publico }}</dd>
                    <dt>Descrição</dt>
                    <dd>{{ modulo.descricao }}</dd>
                </dl>
                <h2>Aulas</h2>
                <ol>
                   {% for aula in aulas %}
                       <li><a href="{{ aula.get_absolute_url }}">{{aula.titulo}}</a></li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
{% endblock body %}

turmas/templates/turmas/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Índice de Turmas{% endblock title %}
{% block description %}Página com todas as turmas do curso Python Pro{% endblock description %}
{% block body %}

    <div class="container">
        {% for modulo in modulos %}
            <div class="row">
                <div class="col-md-12">
                    <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
                    <dl>
                        <dt>Público</dt>
                        <dd>{{ modulo.publico }}</dd>
                        <dt>Descrição</dt>
                        <dd>{{ modulo.descricao }}</dd>
                    </dl>
                    <h2>Aulas</h2>
                    <ol>
                        {% for aula in modulo.aulas %}
                            <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock body %}